language: java
sudo: required
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
  - sudo apt-get install -y libwebkitgtk-3.0-0 || echo no sudo apt-get
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo No X11
  - sleep 3
script:
  - if java -version 2>&1 | grep "1\.8\.0"; then mvn javadoc:javadoc; fi
  - mvn verify -Dmaven.javadoc.skip=true
jdk:
 - openjdk8
 - openjdk11
os:
  - linux
  - osx 
